<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Description>A Puppeteer-sharp provider for iPDFGen</Description>
        <IsPackable>true</IsPackable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
      <PackageReference Include="PuppeteerSharp" Version="25.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\iPDFGen.Core\iPDFGen.Core.csproj" />
    </ItemGroup>
</Project>
