name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and tag Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d)_${{ github.run_number }}
        docker build . --file Dockerfile --tag marisvigulis/ipdfgenserver:$IMAGE_TAG
        docker tag marisvigulis/ipdfgenserver:$IMAGE_TAG marisvigulis/ipdfgenserver:latest
    
    - name: Push Docker image to Docker Hub
      if: github.event_name != 'pull_request'
      run: |
        IMAGE_TAG=$(date +%Y%m%d)_${{ github.run_number }}
        docker push marisvigulis/ipdfgenserver:$IMAGE_TAG
        docker push marisvigulis/ipdfgenserver:latest