name: publish to nuget
on:
  workflow_run:
    workflows: ["build and test"]
    types:
      - completed
    branches:
      - releases/** # Default release branch

jobs:
  publish:
    # Only run if the dotnet workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Extract version
        id: extract_version
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          if [[ $BRANCH_NAME =~ releases/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Error: Branch name doesn't match expected format" >&2
            exit 1
          fi

      - name: Pack iPDFGen.Core
        run: dotnet pack iPDFGen.Core/iPDFGen.Core.csproj -c Release /p:Version=${{ steps.extract_version.outputs.VERSION }} -o ./nupkgs

      - name: Pack iPDFGen.Puppeteer
        run: dotnet pack iPDFGen.Puppeteer/iPDFGen.Puppeteer.csproj -c Release /p:Version=${{ steps.extract_version.outputs.VERSION }} -o ./nupkgs

      - name: Pack iPDFGen.Playwright
        run: dotnet pack iPDFGen.Playwright/iPDFGen.Playwright.csproj -c Release /p:Version=${{ steps.extract_version.outputs.VERSION }} -o ./nupkgs

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json